spring:
  datasource:
    url: jdbc:h2:mem:pruebatecnica
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      mode: always
      data-locations: classpath:/init_data.sql
